### ISSUE TITLE
:bug: Documentation without content

### ISSUE THREAD

**Issue by hamonCordova** [takuma-ru/vue-swipe-modal#68]
### Want to Achieve
The documentation does not have content

**Comment by takuma-ru** [comment]
Oh! That's true.
I think it's because I didn't test the operation because I rushed to get a newer version of NuxtJs.

Thanks so much for reporting the bug!

But sadly, at the moment I'm infected with coronavirus and can't afford to code very much...

The documentation itself is in docs>content in Markdown, so if you want to see the documentation right now, just go to that folder and you'll be able to see it.

I'll do the revisions when I'm feeling better. Please wait a little longer.



DeepLで翻訳しました https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by hamonCordova** [comment]
Thanks for all Takuma. I really want you to get well fast  COVID-19 sucks.
I'm glad to be uselful reporting this bug.

**Comment by takuma-ru** [comment]
# :white_check_mark:This Issue has been resolved.

## Report
Content was not generated because the build setting was `nuxt generate`.
